import { User, Account, Project, Task, Notification } from "@/types";
import { subDays, subHours, addDays, formatISO } from "date-fns";

const now = new Date();

export const SEED_ACCOUNT: Account = {
  id: "acc_taskpilot_demo",
  companyName: "Acme Corp",
  industry: "Software",
  teamSize: 12,
  plan: "pro",
  mrr: 299,
  signupSource: "organic",
  trialEndDate: null,
};

export const SEED_USERS: User[] = [
  {
    id: "user_current",
    email: "alex@acmecorp.io",
    firstName: "Alex",
    lastName: "Rivera",
    role: "admin",
    plan: "pro",
    signupDate: formatISO(subDays(now, 45)),
    lastLogin: formatISO(subHours(now, 2)),
    theme: "system",
  },
  {
    id: "user_2",
    email: "jamie@acmecorp.io",
    firstName: "Jamie",
    lastName: "Chen",
    role: "manager",
    plan: "pro",
    signupDate: formatISO(subDays(now, 40)),
    lastLogin: formatISO(subHours(now, 5)),
    theme: "light",
  },
  {
    id: "user_3",
    email: "morgan@acmecorp.io",
    firstName: "Morgan",
    lastName: "Taylor",
    role: "member",
    plan: "pro",
    signupDate: formatISO(subDays(now, 38)),
    lastLogin: formatISO(subDays(now, 1)),
    theme: "dark",
  },
  {
    id: "user_4",
    email: "sam@acmecorp.io",
    firstName: "Sam",
    lastName: "Patel",
    role: "member",
    plan: "pro",
    signupDate: formatISO(subDays(now, 35)),
    lastLogin: formatISO(subDays(now, 2)),
    theme: "system",
  },
  {
    id: "user_5",
    email: "jordan@acmecorp.io",
    firstName: "Jordan",
    lastName: "Kim",
    role: "member",
    plan: "free",
    signupDate: formatISO(subDays(now, 30)),
    lastLogin: formatISO(subDays(now, 3)),
    theme: "light",
  },
];

export const SEED_PROJECTS: Project[] = [
  {
    id: "proj_1",
    name: "Website Redesign",
    description: "Full redesign of the marketing website with new brand identity",
    status: "active",
    createdAt: formatISO(subDays(now, 30)),
    ownerId: "user_current",
    memberIds: ["user_current", "user_2", "user_3"],
    labelIds: ["label_design", "label_frontend"],
  },
  {
    id: "proj_2",
    name: "Mobile App v2",
    description: "Second version of the mobile application with new features",
    status: "active",
    createdAt: formatISO(subDays(now, 25)),
    ownerId: "user_2",
    memberIds: ["user_2", "user_4", "user_5"],
    labelIds: ["label_mobile", "label_backend"],
  },
  {
    id: "proj_3",
    name: "Q2 Marketing Campaign",
    description: "Campaign planning and execution for Q2",
    status: "active",
    createdAt: formatISO(subDays(now, 20)),
    ownerId: "user_current",
    memberIds: ["user_current", "user_3"],
    labelIds: ["label_marketing"],
  },
  {
    id: "proj_4",
    name: "API Integration",
    description: "Third-party API integrations for the platform",
    status: "active",
    createdAt: formatISO(subDays(now, 15)),
    ownerId: "user_4",
    memberIds: ["user_4", "user_2", "user_current"],
    labelIds: ["label_backend"],
  },
  {
    id: "proj_5",
    name: "Customer Onboarding Flow",
    description: "Revamp the customer onboarding experience",
    status: "active",
    createdAt: formatISO(subDays(now, 10)),
    ownerId: "user_current",
    memberIds: ["user_current", "user_2", "user_3", "user_4"],
    labelIds: ["label_design", "label_frontend"],
  },
  {
    id: "proj_6",
    name: "Legacy Migration",
    description: "Migrate legacy codebase to new infrastructure (archived)",
    status: "archived",
    createdAt: formatISO(subDays(now, 60)),
    ownerId: "user_2",
    memberIds: ["user_2"],
    labelIds: ["label_backend"],
  },
];

export const SEED_TASKS: Task[] = [
  // Website Redesign tasks
  {
    id: "task_1",
    projectId: "proj_1",
    title: "Create new design system",
    description: "Define color tokens, typography scale, and component library",
    status: "done",
    priority: "high",
    assigneeId: "user_3",
    dueDate: formatISO(subDays(now, 5)),
    labels: ["design"],
    comments: [
      { id: "c1", userId: "user_current", body: "Great progress on the tokens!", at: formatISO(subDays(now, 6)) },
    ],
    attachments: ["design-system-v1.fig"],
    createdAt: formatISO(subDays(now, 28)),
    completedAt: formatISO(subDays(now, 5)),
  },
  {
    id: "task_2",
    projectId: "proj_1",
    title: "Redesign landing page hero",
    description: "New hero section with animated gradient and value proposition copy",
    status: "in_progress",
    priority: "urgent",
    assigneeId: "user_current",
    dueDate: formatISO(addDays(now, 2)),
    labels: ["frontend", "design"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 20)),
    completedAt: null,
  },
  {
    id: "task_3",
    projectId: "proj_1",
    title: "Implement responsive navigation",
    description: "Mobile-first nav with hamburger menu and sticky behavior",
    status: "todo",
    priority: "medium",
    assigneeId: "user_2",
    dueDate: formatISO(addDays(now, 7)),
    labels: ["frontend"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 18)),
    completedAt: null,
  },
  {
    id: "task_4",
    projectId: "proj_1",
    title: "Write SEO meta content",
    description: "Optimize all pages with proper meta tags, OG images",
    status: "todo",
    priority: "low",
    assigneeId: null,
    dueDate: formatISO(subDays(now, 2)), // overdue
    labels: ["marketing"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 15)),
    completedAt: null,
  },
  {
    id: "task_5",
    projectId: "proj_1",
    title: "Performance audit",
    description: "Run Lighthouse audit and fix critical issues",
    status: "in_review",
    priority: "high",
    assigneeId: "user_3",
    dueDate: formatISO(addDays(now, 3)),
    labels: ["frontend"],
    comments: [
      { id: "c2", userId: "user_3", body: "Reduced LCP from 4.2s to 1.8s!", at: formatISO(subHours(now, 12)) },
      { id: "c3", userId: "user_current", body: "Nice work! Check the mobile score too.", at: formatISO(subHours(now, 8)) },
    ],
    attachments: ["lighthouse-report.pdf"],
    createdAt: formatISO(subDays(now, 12)),
    completedAt: null,
  },
  // Mobile App tasks
  {
    id: "task_6",
    projectId: "proj_2",
    title: "Set up React Native navigation",
    description: "Configure stack and tab navigators with deep linking",
    status: "done",
    priority: "high",
    assigneeId: "user_4",
    dueDate: formatISO(subDays(now, 10)),
    labels: ["mobile"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 24)),
    completedAt: formatISO(subDays(now, 10)),
  },
  {
    id: "task_7",
    projectId: "proj_2",
    title: "Build push notification system",
    description: "FCM/APNs integration for push notifications",
    status: "in_progress",
    priority: "high",
    assigneeId: "user_5",
    dueDate: formatISO(addDays(now, 5)),
    labels: ["mobile", "backend"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 20)),
    completedAt: null,
  },
  {
    id: "task_8",
    projectId: "proj_2",
    title: "Implement offline mode",
    description: "Cache critical data with AsyncStorage for offline access",
    status: "todo",
    priority: "medium",
    assigneeId: "user_2",
    dueDate: formatISO(subDays(now, 1)), // overdue
    labels: ["mobile"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 18)),
    completedAt: null,
  },
  {
    id: "task_9",
    projectId: "proj_2",
    title: "App store assets and copy",
    description: "Screenshots, icon, description for iOS and Android stores",
    status: "todo",
    priority: "low",
    assigneeId: null,
    dueDate: formatISO(addDays(now, 14)),
    labels: ["marketing"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 14)),
    completedAt: null,
  },
  // Q2 Marketing Campaign tasks
  {
    id: "task_10",
    projectId: "proj_3",
    title: "Campaign strategy document",
    description: "Define target segments, messaging, and KPIs",
    status: "done",
    priority: "urgent",
    assigneeId: "user_current",
    dueDate: formatISO(subDays(now, 15)),
    labels: ["marketing"],
    comments: [{ id: "c4", userId: "user_3", body: "Approved! Let's ship.", at: formatISO(subDays(now, 14)) }],
    attachments: ["q2-strategy.pdf"],
    createdAt: formatISO(subDays(now, 19)),
    completedAt: formatISO(subDays(now, 14)),
  },
  {
    id: "task_11",
    projectId: "proj_3",
    title: "Design email templates",
    description: "5 email templates for drip campaign",
    status: "in_progress",
    priority: "high",
    assigneeId: "user_3",
    dueDate: formatISO(addDays(now, 4)),
    labels: ["design", "marketing"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 14)),
    completedAt: null,
  },
  {
    id: "task_12",
    projectId: "proj_3",
    title: "Set up campaign analytics",
    description: "UTM tracking, conversion pixels, dashboards",
    status: "todo",
    priority: "medium",
    assigneeId: "user_current",
    dueDate: formatISO(addDays(now, 8)),
    labels: ["marketing"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 12)),
    completedAt: null,
  },
  // API Integration tasks
  {
    id: "task_13",
    projectId: "proj_4",
    title: "Stripe payment integration",
    description: "Implement subscription billing with Stripe checkout",
    status: "done",
    priority: "urgent",
    assigneeId: "user_4",
    dueDate: formatISO(subDays(now, 8)),
    labels: ["backend"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 14)),
    completedAt: formatISO(subDays(now, 8)),
  },
  {
    id: "task_14",
    projectId: "proj_4",
    title: "GitHub OAuth integration",
    description: "Allow users to sign in with GitHub",
    status: "in_review",
    priority: "medium",
    assigneeId: "user_2",
    dueDate: formatISO(addDays(now, 1)),
    labels: ["backend"],
    comments: [{ id: "c5", userId: "user_4", body: "Looks good, just need to add error handling.", at: formatISO(subHours(now, 4)) }],
    attachments: [],
    createdAt: formatISO(subDays(now, 10)),
    completedAt: null,
  },
  {
    id: "task_15",
    projectId: "proj_4",
    title: "Slack webhook notifications",
    description: "Send task updates to Slack channels",
    status: "todo",
    priority: "low",
    assigneeId: "user_current",
    dueDate: formatISO(subDays(now, 3)), // overdue
    labels: ["backend"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 9)),
    completedAt: null,
  },
  // Customer Onboarding tasks
  {
    id: "task_16",
    projectId: "proj_5",
    title: "User research interviews",
    description: "10 interviews with new users to understand pain points",
    status: "done",
    priority: "high",
    assigneeId: "user_current",
    dueDate: formatISO(subDays(now, 7)),
    labels: ["design"],
    comments: [],
    attachments: ["interview-notes.pdf"],
    createdAt: formatISO(subDays(now, 9)),
    completedAt: formatISO(subDays(now, 7)),
  },
  {
    id: "task_17",
    projectId: "proj_5",
    title: "Redesign onboarding wizard",
    description: "New 5-step flow based on research findings",
    status: "in_progress",
    priority: "urgent",
    assigneeId: "user_3",
    dueDate: formatISO(addDays(now, 3)),
    labels: ["frontend", "design"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 8)),
    completedAt: null,
  },
  {
    id: "task_18",
    projectId: "proj_5",
    title: "Implement email verification",
    description: "Send verification email on signup",
    status: "todo",
    priority: "medium",
    assigneeId: "user_4",
    dueDate: formatISO(addDays(now, 6)),
    labels: ["backend"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 7)),
    completedAt: null,
  },
  {
    id: "task_19",
    projectId: "proj_5",
    title: "A/B test welcome email",
    description: "Test two subject lines and measure open rates",
    status: "todo",
    priority: "low",
    assigneeId: "user_2",
    dueDate: formatISO(addDays(now, 10)),
    labels: ["marketing"],
    comments: [],
    attachments: [],
    createdAt: formatISO(subDays(now, 6)),
    completedAt: null,
  },
  {
    id: "task_20",
    projectId: "proj_5",
    title: "In-app guide tooltips",
    description: "Implement Pendo guides for key first-time actions",
    status: "in_review",
    priority: "high",
    assigneeId: "user_current",
    dueDate: formatISO(addDays(now, 2)),
    labels: ["frontend"],
    comments: [{ id: "c6", userId: "user_2", body: "The welcome tooltip looks great!", at: formatISO(subHours(now, 6)) }],
    attachments: [],
    createdAt: formatISO(subDays(now, 5)),
    completedAt: null,
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_1",
    userId: "user_current",
    type: "task_assigned",
    message: "Jamie Chen assigned you to 'Redesign landing page hero'",
    read: false,
    createdAt: formatISO(subHours(now, 1)),
    taskId: "task_2",
    projectId: "proj_1",
  },
  {
    id: "notif_2",
    userId: "user_current",
    type: "comment_added",
    message: "Morgan Taylor commented on 'Performance audit'",
    read: false,
    createdAt: formatISO(subHours(now, 3)),
    taskId: "task_5",
    projectId: "proj_1",
  },
  {
    id: "notif_3",
    userId: "user_current",
    type: "due_soon",
    message: "Task 'Redesign landing page hero' is due in 2 days",
    read: true,
    createdAt: formatISO(subHours(now, 8)),
    taskId: "task_2",
    projectId: "proj_1",
  },
  {
    id: "notif_4",
    userId: "user_current",
    type: "task_completed",
    message: "Sam Patel completed 'Stripe payment integration'",
    read: true,
    createdAt: formatISO(subDays(now, 1)),
    taskId: "task_13",
    projectId: "proj_4",
  },
];
